name: recorder
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_sound_lite: ^8.3.9

  permission_handler: ^8.1.3

  flutter_bloc: 7.0.0

  cupertino_icons: ^1.0.2

  stop_watch_timer: ^1.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


